repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]
        additional_dependencies: []
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
        args: ["--config-file=pyproject.toml"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        stages: [post-commit]
      - id: trailing-whitespace
        stages: [post-commit]

  - repo: local
    hooks:
      - id: amend-after-autofix
        name: Amend commit if hooks changed files
        language: system
        pass_filenames: false
        stages: [post-commit]
        entry: bash -c 'git diff --quiet || (git add -A && git commit --amend --no-edit)'
