name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Cache uv & venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync deps (locked)
        run: |
          uv venv
          uv sync --locked

      - name: Ruff (lint)
        run: .venv/bin/ruff check .

      - name: Black (format check)
        run: .venv/bin/black --check .

      - name: MyPy (types)
        run: .venv/bin/mypy src tests

      - name: PyTest
        run: .venv/bin/pytest -q

      - name: Build wheel (artifact)
        run: |
          .venv/bin/python -m pip install -U build
          .venv/bin/python -m build --wheel
        if: always()

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wheel
          path: dist/*.whl
